// src/components/domain/sidebar-icon-map.ts
//
// Registry mapping a serializable string key -> a lucide icon component.
//
// WHY: the sidebar nav config is assembled in the server component
// `src/app/(app)/layout.tsx` (permission-gated `visible` flags need the
// request's permission set) and then passed as props to the client
// `AppSidebar`. React Server Components cannot serialize a function across
// the server/client boundary, so the nav items carry a string icon NAME and
// the client resolves it to a component through this map.

import {
  Accessibility,
  Baby,
  Backpack,
  Bandage,
  BarChart3,
  Bell,
  BookOpen,
  Brain,
  Bus,
  Calculator,
  Calendar,
  Camera,
  CheckCircle2,
  ClipboardList,
  CreditCard,
  DollarSign,
  DoorOpen,
  FileText,
  Files,
  Flower2,
  Footprints,
  GraduationCap,
  Hand,
  Heart,
  Home,
  IdCard,
  Inbox,
  Landmark,
  Languages,
  Leaf,
  Library,
  LifeBuoy,
  Logs,
  Mail,
  Medal,
  Megaphone,
  MessageSquare,
  Mic,
  Newspaper,
  Phone,
  Pill,
  Puzzle,
  Receipt,
  Recycle,
  Repeat,
  Sandwich,
  School,
  Shield,
  Siren,
  Sparkles,
  Sprout,
  SquarePen,
  Star,
  Syringe,
  Timer,
  TrendingDown,
  User,
  Users,
  Wrench,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const SIDEBAR_ICON_MAP = {
  Accessibility,
  Baby,
  Backpack,
  Bandage,
  BarChart3,
  Bell,
  BookOpen,
  Brain,
  Bus,
  Calculator,
  Calendar,
  Camera,
  CheckCircle2,
  ClipboardList,
  CreditCard,
  DollarSign,
  DoorOpen,
  FileText,
  Files,
  Flower2,
  Footprints,
  GraduationCap,
  Hand,
  Heart,
  Home,
  IdCard,
  Inbox,
  Landmark,
  Languages,
  Leaf,
  Library,
  LifeBuoy,
  Logs,
  Mail,
  Medal,
  Megaphone,
  MessageSquare,
  Mic,
  Newspaper,
  Phone,
  Pill,
  Puzzle,
  Receipt,
  Recycle,
  Repeat,
  Sandwich,
  School,
  Shield,
  Siren,
  Sparkles,
  Sprout,
  SquarePen,
  Star,
  Syringe,
  Timer,
  TrendingDown,
  User,
  Users,
  Wrench,
} satisfies Record<string, LucideIcon>;

export type SidebarIconName = keyof typeof SIDEBAR_ICON_MAP;
